<?php
namespace Icerbox\Tests\Auth;

use Icerbox\Auth;

class LoginText extends \PHPUnit_Framework_TestCase {
	/**
	 * @var \Icerbox\Auth\Login
	 */
	protected $_Login = null;

	/**
	 * Config array
	 * @var array
	 */
	protected $_config = null;

	public function setUp() {
		parent::setUp(); // TODO: Change the autogenerated stub
		$this->_Login = new Auth\Login();
		$this->_config = require(__DIR__ . DIRECTORY_SEPARATOR . 'config.php');
	}

	/**
	 * @expectedException \Icerbox\Exception
	 */
	public function testShouldFailWithException() {
		$this->_Login->run(['email' => 'email', 'password' => 'password']);
	}
	/**
	 * Test should login API with user and password from config.php (cp config.default.php config.php)
	 */
	public function testShoudlLoginToApi() {
		$this->assertTrue(is_string($this->_Login->run($this->_config)));
	}
}